package sentinel.gameplay.world
{
	
	/**
	 * A contract describing a Being who can be queried for via the World it is containing in. If a
	 * Being does not implement this interface, it will not appear in any listings generated by 
	 * <code>World.query()</code>.
	 * @author Marty Wallace.
	 */
	public interface IQueryable
	{
		
		//
		
	}
	
}